# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: dbos-cron-starter
language: python
runtimeConfig:
  start:
    - "python3 app/main.py"
database_url: ${DBOS_DATABASE_URL}
database:
  migrate:
    - echo 'No migrations specified'
