[project]
name = "agent-inbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.9.0",
    "dbos>=2.3.0",
    "fastapi>=0.121.0",
    "isort>=7.0.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
